apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keystore
  name: keystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keystore
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keystore
    spec:
      containers:
      - image: nishanta/keystore
        name: keystore
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            port: 8080
            path: /get/abc-1
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: 8080
            path: /get/abc-1
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: keystore
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: keystore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keystore
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: keystore
            port:
              number: 80