apiVersion: batch/v1
kind: Job
metadata:
   name: keystore-status
   annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
   backoffLimit: 3
   template:
     spec:
       restartPolicy: OnFailure
       containers:
          - name: keystore-status-checker
            image: curlimages/curl
            command: ["/bin/sh","-c","[[ $(curl 35.241.63.161/get/abc-1 -s -o /dev/null -w \"%{http_code}\") -eq 200 ]] && exit 0 || exit 1"]